-- MySQL Script generated by MySQL Workbench
-- Fri Oct 27 23:02:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tweets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tweets` DEFAULT CHARACTER SET utf8 ;
USE `tweets` ;

-- -----------------------------------------------------
-- Table `tweets`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweets`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `updated_at` DATETIME NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`id`) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweets`.`tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweets`.`tweets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `text` TEXT(2048) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `updated_at` DATETIME NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `tweet_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `tweet_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `tweets`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweets`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweets`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `tweet_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `deleted_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tweet_id_idx` (`tweet_id` ASC) VISIBLE,
  CONSTRAINT `likes_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `tweets`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tweet_id`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `tweets`.`tweets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
